### PR TITLE
Get position from player

### PR DESCRIPTION
**Pull request by tanyabryn**
Added some new functions and tests, can you check it out? :grimacing:

### CODE REVIEW

**Comment by guttih** [comment]
Code coverage is yellow for lines 51, 55 and 69 in file TickTackToe.java.
This means that not all conditions are tested.  Can you fix that  Tanya.

**Comment by tanyabryn** [comment]
Yes I will take a look at it right now!

**Comment by tanyabryn** [comment]
I fixed the code coverage for lines 51 and 55 but I cannot fix line 69 since this is impossible to test if both of the conditions are true in an or statement the first condition is only checked because it is enough that one of the conditions is true.

**Comment by guttih** [comment]
O, yes I see that it can never happen in line 69. So I'll accept this pull request

**Pull request merged**
