### PR TITLE
Function that plays the game has been added.

### PR DESCRIPTION
**Pull request by tanyabryn**
Can you check this funtion?

### CODE REVIEW

**Comment by tanyabryn** [comment]
Sorry forgot one commit!

**Comment by tanyabryn** [comment]
Ok everything should be right now! :satisfied:

**Comment by saraarnad** [comment]
Why did you comment out the testPrint function? :smiley_cat:

**Comment by tanyabryn** [comment]
woopz! forgot to erase it!

**Comment by tanyabryn** [comment]
Done! :smile:

**Comment by saraarnad** [comment]
NICE! This looks great! :santa:

**Pull request merged**
